export const CORE_TEAM = [
  {
    name: "Hammad Ellahi",
    title: "Founder",
    handle: "@hammadellahi",
    status: "Online",
    avatarUrl: "/team/hammad-ellahi.png",
    linkedin: "https://linkedin.com/in/hammadellahi",
    bio: "The visionary who built Onyx Interactive from the ground up. Hammad's entrepreneurial spirit and deep industry insight laid the foundation for a software house that punches above its weight.",
    skills: ["Entrepreneurship", "Product Vision", "Business Development", "Innovation"],
  },
  {
    name: "Umair Jadoon",
    title: "CEO",
    handle: "@umairjadoon",
    status: "Online",
    avatarUrl: "/team/umair-jadoon.png",
    linkedin: "https://linkedin.com/in/umairjadoon",
    bio: "Visionary leader steering Onyx Interactive's strategic direction. Umair drives the company's mission to deliver world-class digital products that empower businesses and create lasting impact.",
    skills: ["Business Strategy", "Client Relations", "Team Leadership", "Growth"],
  },
  {
    name: "Muhammad Fahad",
    title: "CTO",
    handle: "@muhammadfahad",
    status: "In a meeting",
    avatarUrl: "/team/muhammad-fahad.png",
    linkedin: "https://linkedin.com/in/muhammadfahad",
    bio: "Technical powerhouse behind Onyx's engineering excellence. Muhammad architects scalable systems and drives innovation, ensuring every product we ship meets the highest performance and security standards.",
    skills: ["Cloud Architecture", "System Design", "React / Next.js", "DevOps"],
  },
  {
    name: "Syed Raza Ali Gillani",
    title: "Finance Manager",
    handle: "@syedrazaaligillani",
    status: "Online",
    avatarUrl: "/team/syed-raza-ali-gillani.png",
    linkedin: "https://linkedin.com/in/syedrazaaligillani",
    bio: "Finance expert ensuring Onyx's financial health and operational efficiency. Syed manages P&L, client contracts, and guarantees every project delivers value without compromising quality.",
    skills: ["Financial Planning", "Contract Management", "Budget Oversight", "Risk Analysis"],
  },
  {
    name: "Muhammad Hammad",
    title: "Project Manager IT",
    handle: "@muhammadhammad",
    status: "Busy",
    avatarUrl: "/team/muhammad-hammad.png",
    linkedin: "https://linkedin.com/in/muhammadhammad",
    bio: "PMP-certified project manager with deep expertise in agile delivery. Muhammad ensures IT projects run on time, on budget, and on scope — keeping clients informed and the team aligned.",
    skills: ["Agile / Scrum", "JIRA", "Client Communication", "Risk Management"],
  },
  {
    name: "Talha Mujahid",
    title: "Project Manager E-Commerce",
    handle: "@talhamujahid",
    status: "Busy",
    avatarUrl: "/team/talha-mujhaid.png",
    linkedin: "https://linkedin.com/in/talhamujahid",
    bio: "E-commerce delivery specialist with a track record of launching high-converting storefronts. Talha drives conversion-focused build cycles and post-launch growth strategies for our retail clients.",
    skills: ["Shopify / WooCommerce", "CRO", "Vendor Management", "Digital Strategy"],
  },
  {
    name: "Samiullah Khan",
    title: "Office Administrator",
    handle: "@samiullahkhan",
    status: "Available",
    avatarUrl: "/team/samiullah-khan.png",
    linkedin: "https://linkedin.com/in/samiullahkhan",
    bio: "The backbone of our workspace. Samiullah keeps operations running smoothly — from logistics and vendor management to coordinating in-person meetings — ensuring the team always has what it needs to deliver.",
    skills: ["Facilities Management", "Logistics", "Team Support", "Office Operations"],
  },
  {
    name: "Hafsa Azhar",
    title: "Digital Marketing Intern",
    handle: "@hafsaazhar",
    status: "Online",
    avatarUrl: "/team/hafsa-azhar.png",
    linkedin: "https://linkedin.com/in/hafsaazhar",
    bio: "Digital marketing intern driving Onyx's social strategy, brand awareness, and online content campaigns with creative momentum.",
    skills: ["Digital Marketing", "Content Strategy", "SEO", "Social Media"],
  },
  {
    name: "Muhammad Ehtisham Anwar",
    title: "Fullstack Intern",
    handle: "@muhammadehtishamanwar",
    status: "Online",
    avatarUrl: "/team/muhammad-ehtisham-anwar.png",
    linkedin: "https://linkedin.com/in/muhammadehtishamanwar",
    bio: "Fullstack engineering intern working across modern frontend frameworks and backend web services to deliver seamless features.",
    skills: ["React / Next.js", "Node.js", "TypeScript", "REST APIs"],
  },
  {
    name: "Anum Shahzadi",
    title: "Frontend and AI Automation Intern",
    handle: "@anumshahzadi",
    status: "Online",
    avatarUrl: "/team/anum-shahzadi.png",
    linkedin: "https://linkedin.com/in/anumshahzadi",
    bio: "Frontend and AI automation intern building responsive web interfaces and integrating intelligent workflow automation solutions.",
    skills: ["Frontend Dev", "AI Automation", "React", "Python"],
  },
  {
    name: "Naveed Ahmed",
    title: "Frontend Intern",
    handle: "@naveedahmed",
    status: "Online",
    avatarUrl: "/team/naveed-ahmed.png",
    linkedin: "https://linkedin.com/in/naveedahmed",
    bio: "Frontend engineering intern focused on crafting pixel-perfect, interactive UI components and high-performance layouts.",
    skills: ["Frontend Dev", "Tailwind CSS", "JavaScript", "React"],
  },
];
